name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Configure npm for public registry
      run: |
        npm config set registry https://registry.npmjs.org/
        npm config set //registry.npmjs.org/:_authToken=""
        echo "Configured npm to use public registry for security scanning"

    - name: Security scan dependencies (root)
      run: |
        if [ -f "package.json" ]; then
          echo "Scanning root package.json for vulnerabilities..."
          npm audit --registry=https://registry.npmjs.org --audit-level=moderate || echo "npm audit completed with findings"
        else
          echo "No package.json found in root"
        fi
      continue-on-error: true

    - name: Security scan dependencies (website)
      run: |
        if [ -f "website/package.json" ]; then
          echo "Scanning website package.json for vulnerabilities..."
          cd website && npm audit --registry=https://registry.npmjs.org --audit-level=moderate || echo "npm audit completed with findings"
        else
          echo "No package.json found in website"
        fi
      continue-on-error: true

    - name: Security scan dependencies (point-solutions)
      run: |
        if [ -f "src/point-solutions/libraries/package.json" ]; then
          echo "Scanning point-solutions package.json for vulnerabilities..."
          cd src/point-solutions/libraries && npm audit --registry=https://registry.npmjs.org --audit-level=moderate || echo "npm audit completed with findings"
        else
          echo "No package.json found in point-solutions"
        fi
      continue-on-error: true

    # CodeQL analysis is handled by GitHub's default setup
    # Custom CodeQL steps removed to avoid conflicts

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        
    - name: Run Trivy vulnerability scanner (JSON output)
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'json'
        output: 'trivy-results.json'
        exit-code: '0'

    - name: Upload Trivy results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-results
        path: trivy-results.json
        retention-days: 30

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-3.0, LGPL-2.1, LGPL-3.0